apiVersion: v1
data:
  mapRoles: |
   - groups:
      - system:masters
      rolearn: arn:aws:iam::800328424226:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-27T16:00:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1708"
  uid: 1bcecaf5-3154-4f37-958d-71a2985e77aa
